### ISSUE TITLE
Profiler class was not successfully injected

### ISSUE THREAD

**Issue by lzccc** [spideruci/blinky-core#3]
https://github.com/spideruci/blinky-core/blob/f7132daed5f86004ddcf72f569658c8678084aca/src/org/spideruci/analysis/statik/instrumentation/Config.java#L9-L14
After compiling the blinky-core, the `exclusionList` and `inclusionList` were injected successfully and we don't need to initialize those two arrays in the source code. But now the profiler is still null and we still need to initialize the variable first to let the program run. Could you give us more explanations on how to inject profilers into Config.java?

**Comment by kajdreef** [comment]
@lzccc I think this question was answered in the video Jim shared with us on the slack channel. Maybe see if that clears it up? Else @VijayKrishna could maybe help out?

**Comment by VijayKrishna** [comment]
@lzccc can you describe what you did to inject the profiler class? Editing blinky-core's pom.xml should get you there. Specifically, making edits to the following lines in the pom.xml file should do the trick:

```
       <key>config.profilerclassname</key>
       <value>org.spideruci.analysis.dynamic.profilers.MethodCallsTracker</value>
```
